env: flex
runtime: nodejs
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  http_headers:
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'